version: '2'
services:
    ecommerce-app:
        image: ecommerce
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://ecommerce-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8888:8888
    ecommerce-mssql:
        extends:
            file: mssql.yml
            service: ecommerce-mssql
